### ISSUE TITLE
Merge Hydroshare 1.14 Release

### ISSUE THREAD

**Issue by cbcunc** [myhpom/MyHPOM#80]
First into a separate branch, test, and if that works, into xdci-develop.

**Comment by dsummersl** [comment]
Issues that Chris saw on the dev branch:

- [x] the organization field has returned to the signup form.
- [x] every time I click on anything in dev, a small red error message box appears at the top of the screen with no text in it, and then it disappears about as fast as it appeared. I’ve never seen this before.
- [x] on create resource, a “select a resource type” field is present with only Document as a selection instead of just telling me it’s a Document with no message to select.
- [ ] the profile nag message from HS 1.14 is not appearing. That might be the momentary error modal, just without the nag text and disappearing without being explicitly dismissed. I’m going to complete a profile to see.
- [x] when I try to save a profile, I see a pink band across the top saying “Error” and below it some smaller text saying “Sorry, an error has occurred.”

**Comment by cbcunc** [comment]
Well done, @dsummersl!
